import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GoogleOauthContainer from "@/Components/GoogleOauthContainer";
import ReactQueryContainer from "@/Components/ReactQueryContainer";
import "./globals.css";
import TwitterLayout from "@/Layout/TwitterLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryContainer>
          <GoogleOauthContainer>
            <TwitterLayout>{children}</TwitterLayout>
          </GoogleOauthContainer>
        </ReactQueryContainer>
      </body>
    </html>
  );
}
